services:
  - type: web
    name: django-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Myproject.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Myproject.settings
      - key: SECRET_KEY
        value: django-insecure-p3r^mt6$kku3(=cot$mqvjt8srh%-4xp6ws6fyxoh+&gnf+v#9
      - key: DEBUG
        value: "False"
      # Render sets DATABASE_URL automatically, so no need to add it manually.
