# Generated by Django 5.1.5 on 2025-03-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Protein', 'Protein'), ('Genome', 'Genome'), ('Nucleotide', 'Nucleotide'), ('Taxonomy', 'Taxonomy'), ('PubChem', 'PubChem'), ('BLAST', 'BLAST')], default='Protein', max_length=20),
        ),
    ]
